# Generated by Django 5.0.3 on 2024-05-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FirstOrderDate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ItemId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Descriptions', models.CharField(max_length=255)),
                ('Size', models.CharField(max_length=20)),
                ('Weight', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.CreateModel(
            name='RepresentativeOffices',
            fields=[
                ('CityId', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=50)),
                ('OfficeAddress', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'RepresentativeOffices',
            },
        ),
        migrations.CreateModel(
            name='PostalCustomers',
            fields=[
                ('CustomerId', models.OneToOneField(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customers')),
                ('PostAddress', models.CharField(max_length=50)),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'PostalCustomers',
            },
        ),
        migrations.CreateModel(
            name='TravelCustomers',
            fields=[
                ('CustomerId', models.OneToOneField(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customers')),
                ('TourGuide', models.CharField(max_length=50)),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'TravelCustomers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('CustomerId', models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, to='app.customers')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderedQuantity', models.IntegerField()),
                ('OrderCost', models.IntegerField()),
                ('Time', models.DateField(null=True)),
                ('ItemId', models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.CASCADE, to='app.items')),
                ('OrderId', models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
            options={
                'db_table': 'OrderedItems',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='CityId',
            field=models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='app.representativeoffices'),
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('StoreId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Time', models.DateField(null=True)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='app.representativeoffices')),
            ],
            options={
                'db_table': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoredItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoredQuantity', models.IntegerField()),
                ('Time', models.DateField(null=True)),
                ('ItemId', models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.CASCADE, to='app.items')),
                ('StoreId', models.ForeignKey(db_column='StoreId', on_delete=django.db.models.deletion.CASCADE, to='app.stores')),
            ],
            options={
                'db_table': 'StoredItems',
            },
        ),
        migrations.AddConstraint(
            model_name='ordereditems',
            constraint=models.UniqueConstraint(fields=('ItemId', 'OrderId'), name='OrderedItemKey'),
        ),
        migrations.AddConstraint(
            model_name='storeditems',
            constraint=models.UniqueConstraint(fields=('ItemId', 'StoreId'), name='StoredItemKey'),
        ),
    ]
